INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES
('coke', 'Coke', 50, 0, 1),
('coke_pooch', 'Pochon de coke', 10, 0, 1),
('crack', 'Crack', 50, 0, 1),
('crack_pooch', 'Pochon de Crack', 10, 0, 1),
('ecstasy', 'Ecstasy', 50, 0, 1),
('ecstasy_pooch', 'Pochon decstasy', 10, 0, 1),
('ketamine', 'Ketamine', 50, 0, 1),
('ketamine_pooch', 'Pochon de ketamine', 10, 0, 1),
('meth', 'meth', 50, 0, 1),
('meth_pooch', 'Pochon de meth', 10, 0, 1),
('acetone', 'Acetone', 50, 0, 1),
('lithium', 'Lithium', 50, 0, 1),
('methlab', 'Methilamine', 50, 0, 1),
('opium', 'Opium', 50, 0, 1),
('opium_pooch', 'Pochon de opium', 10, 0, 1),
('weed', 'Weed', 50, 0, 1),
('weed_pooch', 'Pochon de weed', 10, 0, 1),
('billet', 'Papier', 50, 0, 1),
('billet_pooch', 'Faux Billet', 10, 0, 1)
;